# Chapter 08 "Exception Handling"
## 1. 프로그램 오류
## 1.1. 오류 구분
* 컴파일 에러: 컴파일 시에 발생하는 에러
* 런타임 에러: 실행 시에 발생하는 에러
* 논리적 에러: 컴파일도 실행도 되지만, 의도와 다르게 동작하는 것

## 1.2. 런타임 오류 구분
* 에러: 프로그램 코드에 의해서 수습될 수 있는 심각한 오류 (예: OutOfMemoryError, StackOverflowError)
* 예외: 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

# 2. 예외 클래스의 계층 구조
* RuntimeException 클래스 - 프로그래머의 실수에 의해 발생, 예외처리 필수
    * 예) IndexOutOfBoundException, NullPointException, ClassCastException, ArithmeticException
* Exception 클래스 - 사용자의 실수와 같은 외적인 요인에 의해 발생, 예외처리 선택
    * 예) FileNotFountException, ClassNotFoundException, DataFormatException
* 모든 예외 클래스는 Excepion 클래스의 자손

# 3. 예외 처리하기 "try-catch 문"
## 3.1. 예외 처리의 정의와 목적
* 정의: 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
* 목적: 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것

## 3.2. try-catch문
* 하나 이상의 catch 블럭 중, 발생한 예외 종류와 일치하는 단 한 개의 catch 블럭만 수행됨
* catch 블럭의 괄호 내 선언된 변수는 catch 블럭 내에서만 유효하기 때문에, 참조변수 e 여러번 사용해도 됨

# 4. try-catch문에서의 흐름
* try 블럭 내에서 예외가 발생한 경우 
    * 일치하는 catch 블럭 내의 문장을 수행하고, 예외 발생한 위치 이후에 있는 try 블럭의 문장들은 수행되지 않음
    * 일치하는 catch 블럭을 찾지 못하면, 예외 처리 불가
* try 블럭 내에서 예외가 발생하지 않은 경우
    * catch 블럭 거치지 않고 수행 계속함

# 5. 예외의 발생과 catch 블럭
## 5.1. catch 블럭
* 예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어짐
* catch 블럭의 () 내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof 연산자를 이용하여 검사
* 검사 결과가 true인 catch 블럭에서 예외 처리
* 예외의 최고 조상인 Exception을 처리하는 catch블럭은 모든 종류의 예외를 처리할 수 있음(반드시 마지막 catch블럭이어야 함)

## 5.2. printStackTrace()와 getMessage()
* 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨있음
* catch블럭의 참조변수(e)를 통해 이 인스턴스에 접근할 수 있음
* printStackTrace(): 예외 발생 당시의 호출 스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력
* getMessage(): 발생한 예외 크래스의 인스턴스에 저장된 메시지를 얻을 수 있음




